#!/usr/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



def fib(n):
    fib = [1, 2]
    while fib[-1] < n:
        fib.append(fib[-1] + fib[-2])
        #if fib[-1] >n:
        #    break
    return fib

def sumEven(list):
    sum = 0
    for i in list:
        if i % 2 == 0:
            sum = sum + i
    return sum



vals =  fib(4000000)
print vals
print sumEven(vals)
